export const REQUEST_START = "REQUEST_START";
export const REQUEST_ERROR = "REQUEST_ERROR";
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
